export const GET_CAFES_REQUEST = 'GET_CAFES_REQUEST';
export const GET_CAFES_REQUEST_SUCCESS = 'GET_CAFES_REQUEST_SUCCESS';
export const GET_CAFES_REQUEST_FAIL = 'GET_CAFES_REQUEST_FAIL';

export const ADD_CAFE_REQUEST = 'ADD_CAFE_REQUEST';
export const ADD_CAFE_REQUEST_SUCCESS = 'ADD_CAFE_REQUEST_SUCCESS';
export const ADD_CAFE_REQUEST_FAIL = 'ADD_CAFE_REQUEST_FAIL';

export const UPDATE_CAFE_REQUEST = 'UPDATE_CAFE_REQUEST';
export const UPDATE_CAFE_REQUEST_SUCCESS = 'UPDATE_CAFE_REQUEST_SUCCESS';
export const UPDATE_CAFE_REQUEST_FAIL = 'UPDATE_CAFE_REQUEST_FAIL';

export const DELETE_CAFE_REQUEST = 'DELETE_CAFE_REQUEST';
export const DELETE_CAFE_REQUEST_SUCCESS = 'DELETE_CAFE_REQUEST_SUCCESS';
export const DELETE_CAFE_REQUEST_FAIL = 'DELETE_CAFE_REQUEST_FAIL';

