export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_REQUEST_SUCCESS = 'GET_EMPLOYEES_REQUEST_SUCCESS';
export const GET_EMPLOYEES_REQUEST_FAIL = 'GET_EMPLOYEES_REQUEST_FAIL';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_REQUEST_SUCCESS = 'ADD_EMPLOYEE_REQUEST_SUCCESS';
export const ADD_EMPLOYEE_REQUEST_FAIL = 'ADD_EMPLOYEE_REQUEST_FAIL';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_REQUEST_SUCCESS = 'UPDATE_EMPLOYEE_REQUEST_SUCCESS';
export const UPDATE_EMPLOYEE_REQUEST_FAIL = 'UPDATE_EMPLOYEE_REQUEST_FAIL';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_REQUEST_SUCCESS = 'DELETE_EMPLOYEE_REQUEST_SUCCESS';
export const DELETE_EMPLOYEE_REQUEST_FAIL = 'DELETE_EMPLOYEE_REQUEST_FAIL';
